# Pandas 한번에 제대로 배우기




---



In [2]:
import numpy as np
import pandas as pd
pd.__version__

'1.1.3'

## Pandas 객체


### Series 객체

In [3]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0])
s

0    0.00
1    0.25
2    0.50
3    0.75
4    1.00
dtype: float64

In [4]:
s.values

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [5]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [6]:
s[1]

0.25

In [7]:
s[1:4]

1    0.25
2    0.50
3    0.75
dtype: float64

In [8]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0],
             index = ['a', 'b', 'c', 'd', 'e'])
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [9]:
s['c']

0.5

In [10]:
s[['c', 'd', 'e']]

c    0.50
d    0.75
e    1.00
dtype: float64

In [11]:
'b' in s

True

In [12]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0],
             index = [2, 4, 6, 8, 10])
s

2     0.00
4     0.25
6     0.50
8     0.75
10    1.00
dtype: float64

In [13]:
s[4]

0.25

In [14]:
s[2:]

6     0.50
8     0.75
10    1.00
dtype: float64

In [15]:
s.unique()

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
s.value_counts()

1.00    1
0.75    1
0.50    1
0.25    1
0.00    1
dtype: int64

In [17]:
s.isin([0.25, 0.75])

2     False
4      True
6     False
8      True
10    False
dtype: bool

In [18]:
pop_tuple = {'서울특별시' : 9720846,
            '부산광역시' : 3404423,
            '인천광역시' : 2947217,
            '대구광역시' : 2427945,
            '대전광역시' : 1471040,
            '광주광역시' : 1455048}
population = pd.Series(pop_tuple)
population

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
대구광역시    2427945
대전광역시    1471040
광주광역시    1455048
dtype: int64

In [19]:
population['서울특별시']

9720846

In [20]:
population['서울특별시':'인천광역시']

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
dtype: int64

### DataFrame 객체

In [21]:
pd.DataFrame([{'A':2, 'B':4, 'D':3},{'A':4, 'B':5, 'C':7}])

A  B    D    C
0  2  4  3.0  NaN
1  4  5  NaN  7.0

In [22]:
pd.DataFrame(np.random.rand(5, 5),
            columns = ['A', 'B', 'C','D', 'E'],
            index = [1, 2, 3, 4, 5])

A         B         C         D         E
1  0.961484  0.105660  0.944072  0.007193  0.045677
2  0.142902  0.381848  0.304746  0.166387  0.133895
3  0.771594  0.420042  0.530816  0.417153  0.410853
4  0.209298  0.962196  0.923167  0.233172  0.557488
5  0.424705  0.472575  0.043230  0.094002  0.041118

In [23]:
male_tuple = {'서울특별시' : 4732275,
            '부산광역시' : 1668618,
            '인천광역시' : 1476813,
            '대구광역시' : 1198815,
            '대전광역시' : 734441,
            '광주광역시' : 720060}
male = pd.Series(male_tuple)
male

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
dtype: int64

In [24]:
female_tuple = {'서울특별시' : 4988571,
            '부산광역시' : 1735805,
            '인천광역시' : 1470404,
            '대구광역시' : 1229139,
            '대전광역시' : 736599,
            '광주광역시' : 734988}
female = pd.Series(female_tuple)
female

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
dtype: int64

In [25]:
korea_df = pd.DataFrame({'인구수' : population,
                        '남자인구수' : male,
                        '여자인구수' : female})
korea_df

인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404
대구광역시  2427945  1198815  1229139
대전광역시  1471040   734441   736599
광주광역시  1455048   720060   734988

In [26]:
korea_df.index

Index(['서울특별시', '부산광역시', '인천광역시', '대구광역시', '대전광역시', '광주광역시'], dtype='object')

In [27]:
korea_df.columns

Index(['인구수', '남자인구수', '여자인구수'], dtype='object')

In [28]:
korea_df['여자인구수']

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
Name: 여자인구수, dtype: int64

In [29]:
korea_df['서울특별시':'인천광역시']

인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404

### Index 객체


In [30]:
idx = pd.Index([2, 4, 6, 8, 10])
idx

Int64Index([2, 4, 6, 8, 10], dtype='int64')

In [31]:
idx[1]

4

In [32]:
idx[1:2:2]

Int64Index([4], dtype='int64')

In [33]:
idx[-1::]

Int64Index([10], dtype='int64')

In [34]:
idx[::2]

Int64Index([2, 6, 10], dtype='int64')

In [35]:
print(idx)
print(idx.size)
print(idx.shape)
print(idx.ndim)
print(idx.dtype)

Int64Index([2, 4, 6, 8, 10], dtype='int64')
5
(5,)
1
int64


#### Index 연산

|연산자|메소드|설명|
|:--|:--|:--|
|  |append|색인 객채를 추가한 새로운 색인 반환|
|  |difference|색인의 차집합 반환|
|&|intersection|색인의 교집합 반환|
|\||union|색인의 합집합 반환|
|^|   |색인의 여집합 반환|
|  |delete|색인이 삭제된 새로운 색인 반환|
|  |drop|값이 삭제된 새로운 색인 반환|
|  |insert|색인이 추가된 새로운 색인 반환|
|  |is_monotonic|색인이 단조성을 가지면 True|
|  |is_unique|중복되는 색인이 없단면 True|
|  |unique|색인에서 중복되는 요소를 제거하고 유일한 값만 반환|

In [36]:
idx1 = pd.Index([1, 2, 4, 6, 8])
idx2 = pd.Index([2, 4, 5, 6, 7])
print(idx1.append(idx2))
print(idx1.difference(idx2))
print(idx1 - idx2)
print(idx1.intersection(idx2))
print(idx1 & idx2)
print(idx1.union(idx2))
print(idx1 | idx2)
print(idx1.delete(0))
print(idx1.drop(1))
print(idx1 ^ idx2)

Int64Index([1, 2, 4, 6, 8, 2, 4, 5, 6, 7], dtype='int64')
Int64Index([1, 8], dtype='int64')
Int64Index([-1, -2, -1, 0, 1], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([2, 4, 6, 8], dtype='int64')
Int64Index([2, 4, 6, 8], dtype='int64')
Int64Index([1, 5, 7, 8], dtype='int64')




---



## 인덱싱(Indexing)

In [37]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0],
             index = ['a', 'b', 'c', 'd', 'e'])
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [38]:
s['b']

0.25

In [39]:
'b' in s

True

In [40]:
s.keys()

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [41]:
list(s.items())

[('a', 0.0), ('b', 0.25), ('c', 0.5), ('d', 0.75), ('e', 1.0)]

In [42]:
s['f'] = 1.25
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
f    1.25
dtype: float64

In [43]:
s['a':'d']

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [44]:
s[0:4]

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [45]:
s[(s > 0.4) & (s < 0.8)]

c    0.50
d    0.75
dtype: float64

In [46]:
s[['a', 'c', 'e']]

a    0.0
c    0.5
e    1.0
dtype: float64

### Series 인덱싱

In [47]:
s = pd.Series(['a', 'b', 'c', 'd', 'e'],
             index = [1, 3, 5, 7, 9])
s

1    a
3    b
5    c
7    d
9    e
dtype: object

In [48]:
s[1]

'a'

In [49]:
s[2:4]

5    c
7    d
dtype: object

In [50]:
s.iloc[1]

'b'

In [51]:
s.iloc[2:4]

5    c
7    d
dtype: object

In [52]:
s.reindex(range(10))

0    NaN
1      a
2    NaN
3      b
4    NaN
5      c
6    NaN
7      d
8    NaN
9      e
dtype: object

In [53]:
s.reindex(range(10), method = 'bfill')

0    a
1    a
2    b
3    b
4    c
5    c
6    d
7    d
8    e
9    e
dtype: object

### DataFrame 인덱싱


|사용방법|설명|
|:---|:--|
|df[val]|하나의 컬럼 또는 여러 컬럼을 선택|
|df.loc[val]|라벨값으로 로우의 부분집합 선택|
|df.loc[:,val]|라벨값으로 컬럼의 부분집합 선택|
|df.loc[val1, val2]|라벨값으로 로우와 컬럼의 부분집합 선택|
|df.iloc[:, where]|정수 색인으로 로우의 부분집합 선택|
|df.iloc[where_i, label_j]|정수 색인으로 컬럼의 부분집합 선택|
|df.at[label_i, label_j]|로우와 컬럼의 라벨로 단일 값 선택|
|df.iat[i, j]|로우와 컬럼의 정수 색인으로 단일 값 선택|
|reindex|하나 이상의 축을 새로운 색인으로 재색인|
|get_value, set_value|로우와 컬럼의 이름으로 값 선택|

In [54]:
korea_df

인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404
대구광역시  2427945  1198815  1229139
대전광역시  1471040   734441   736599
광주광역시  1455048   720060   734988

In [55]:
korea_df['남자인구수']

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
Name: 남자인구수, dtype: int64

In [56]:
korea_df.남자인구수

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
Name: 남자인구수, dtype: int64

In [57]:
korea_df.여자인구수

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
Name: 여자인구수, dtype: int64

In [58]:
korea_df['남여비율'] = (korea_df['남자인구수']*100 / korea_df['여자인구수']) 

In [59]:
korea_df.남여비율

서울특별시     94.862336
부산광역시     96.129346
인천광역시    100.435867
대구광역시     97.532907
대전광역시     99.707032
광주광역시     97.968946
Name: 남여비율, dtype: float64

In [60]:
korea_df.values

array([[9.72084600e+06, 4.73227500e+06, 4.98857100e+06, 9.48623363e+01],
       [3.40442300e+06, 1.66861800e+06, 1.73580500e+06, 9.61293463e+01],
       [2.94721700e+06, 1.47681300e+06, 1.47040400e+06, 1.00435867e+02],
       [2.42794500e+06, 1.19881500e+06, 1.22913900e+06, 9.75329072e+01],
       [1.47104000e+06, 7.34441000e+05, 7.36599000e+05, 9.97070319e+01],
       [1.45504800e+06, 7.20060000e+05, 7.34988000e+05, 9.79689464e+01]])

In [61]:
korea_df.T

서울특별시         부산광역시         인천광역시         대구광역시         대전광역시  \
인구수    9.720846e+06  3.404423e+06  2.947217e+06  2.427945e+06  1.471040e+06   
남자인구수  4.732275e+06  1.668618e+06  1.476813e+06  1.198815e+06  7.344410e+05   
여자인구수  4.988571e+06  1.735805e+06  1.470404e+06  1.229139e+06  7.365990e+05   
남여비율   9.486234e+01  9.612935e+01  1.004359e+02  9.753291e+01  9.970703e+01   

              광주광역시  
인구수    1.455048e+06  
남자인구수  7.200600e+05  
여자인구수  7.349880e+05  
남여비율   9.796895e+01

In [62]:
korea_df.values[0]

array([9.72084600e+06, 4.73227500e+06, 4.98857100e+06, 9.48623363e+01])

In [63]:
korea_df['인구수']

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
대구광역시    2427945
대전광역시    1471040
광주광역시    1455048
Name: 인구수, dtype: int64

In [64]:
korea_df.loc[:'인천광역시', :'남자인구수']

인구수    남자인구수
서울특별시  9720846  4732275
부산광역시  3404423  1668618
인천광역시  2947217  1476813

In [65]:
korea_df.loc[(korea_df.여자인구수 > 1000000)]

인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867
대구광역시  2427945  1198815  1229139   97.532907

In [66]:
korea_df.loc[(korea_df.인구수 < 2000000)]

인구수   남자인구수   여자인구수       남여비율
대전광역시  1471040  734441  736599  99.707032
광주광역시  1455048  720060  734988  97.968946

In [67]:
korea_df.loc[(korea_df.인구수 > 2500000)]

인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867

In [68]:
korea_df.loc[korea_df.남여비율 > 100]

인구수    남자인구수    여자인구수        남여비율
인천광역시  2947217  1476813  1470404  100.435867

In [69]:
korea_df.loc[(korea_df.인구수 > 2500000) & (korea_df.남여비율 < 100)]

인구수    남자인구수    여자인구수       남여비율
서울특별시  9720846  4732275  4988571  94.862336
부산광역시  3404423  1668618  1735805  96.129346

In [70]:
korea_df.iloc[:3, :2]

인구수    남자인구수
서울특별시  9720846  4732275
부산광역시  3404423  1668618
인천광역시  2947217  1476813

### 다중 인덱싱(Multi Indexing)

* 1차원의 Series와 2차원의 DataFrame 객체를 넘어 3차원, 4차원 이상의 고차원 데이터 처리
* 단일 인덱스 내에 여러 인덱스를 포함하는 다중 인덱싱

#### 다중 인덱스 Series

In [71]:
korea_df

인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867
대구광역시  2427945  1198815  1229139   97.532907
대전광역시  1471040   734441   736599   99.707032
광주광역시  1455048   720060   734988   97.968946

In [75]:
idx_tuples = [('서울특별시', 2010), ('서울특별시',2020),
               ('부산광역시', 2010), ('부산광역시',2020),
               ('인천광역시', 2010), ('인천광역시',2020),
               ('대구광역시', 2010), ('대구광역시',2020),
               ('대전광역시', 2010), ('대전광역시',2020),
               ('광주광역시', 2010), ('광주광역시',2020)]
idx_tuples

[('서울특별시', 2010),
 ('서울특별시', 2020),
 ('부산광역시', 2010),
 ('부산광역시', 2020),
 ('인천광역시', 2010),
 ('인천광역시', 2020),
 ('대구광역시', 2010),
 ('대구광역시', 2020),
 ('대전광역시', 2010),
 ('대전광역시', 2020),
 ('광주광역시', 2010),
 ('광주광역시', 2020)]

In [76]:
pop_tuples = [10312545, 9720846,
              2567910, 3404423,
              2758296, 2947217,
              2511676, 2427954,
              1503664, 1471040,
              1454636, 1455048]
population = pd.Series(pop_tuples, index = idx_tuples)
population

(서울특별시, 2010)    10312545
(서울특별시, 2020)     9720846
(부산광역시, 2010)     2567910
(부산광역시, 2020)     3404423
(인천광역시, 2010)     2758296
(인천광역시, 2020)     2947217
(대구광역시, 2010)     2511676
(대구광역시, 2020)     2427954
(대전광역시, 2010)     1503664
(대전광역시, 2020)     1471040
(광주광역시, 2010)     1454636
(광주광역시, 2020)     1455048
dtype: int64

In [79]:
midx = pd.MultiIndex.from_tuples(idx_tuples)
midx

MultiIndex([('서울특별시', 2010),
            ('서울특별시', 2020),
            ('부산광역시', 2010),
            ('부산광역시', 2020),
            ('인천광역시', 2010),
            ('인천광역시', 2020),
            ('대구광역시', 2010),
            ('대구광역시', 2020),
            ('대전광역시', 2010),
            ('대전광역시', 2020),
            ('광주광역시', 2010),
            ('광주광역시', 2020)],
           )

In [80]:
population = population.reindex(midx)
population

서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [81]:
population[:, 2010]

서울특별시    10312545
부산광역시     2567910
인천광역시     2758296
대구광역시     2511676
대전광역시     1503664
광주광역시     1454636
dtype: int64

In [82]:
population['대전광역시',:]

2010    1503664
2020    1471040
dtype: int64

In [83]:
korea_mdf = population.unstack()
korea_mdf

2010     2020
광주광역시   1454636  1455048
대구광역시   2511676  2427954
대전광역시   1503664  1471040
부산광역시   2567910  3404423
서울특별시  10312545  9720846
인천광역시   2758296  2947217

In [85]:
korea_mdf.stack()

광주광역시  2010     1454636
       2020     1455048
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
부산광역시  2010     2567910
       2020     3404423
서울특별시  2010    10312545
       2020     9720846
인천광역시  2010     2758296
       2020     2947217
dtype: int64

In [87]:
male_tuples = [5111259, 4732275,
              1773170, 1668618,
              1390356, 1476813,
              1255245, 1198815,
              753648, 734441,
              721780, 720060]
male_tuples

[5111259,
 4732275,
 1773170,
 1668618,
 1390356,
 1476813,
 1255245,
 1198815,
 753648,
 734441,
 721780,
 720060]

In [89]:
korea_mdf = pd.DataFrame({'총인구수' : population,
                          '남자인구수' : male_tuples})
korea_mdf

총인구수    남자인구수
서울특별시 2010  10312545  5111259
      2020   9720846  4732275
부산광역시 2010   2567910  1773170
      2020   3404423  1668618
인천광역시 2010   2758296  1390356
      2020   2947217  1476813
대구광역시 2010   2511676  1255245
      2020   2427954  1198815
대전광역시 2010   1503664   753648
      2020   1471040   734441
광주광역시 2010   1454636   721780
      2020   1455048   720060

In [90]:
female_tuples = [5201286, 4988571,
                 1794740, 1735805,
                 1367940, 1470404,
                 1256431, 1229139,
                 750016, 736599,
                 732856, 734988]
female_tuples

[5201286,
 4988571,
 1794740,
 1735805,
 1367940,
 1470404,
 1256431,
 1229139,
 750016,
 736599,
 732856,
 734988]

In [91]:
korea_mdf = pd.DataFrame({'총인구수' : population,
                          '남자인구수' : male_tuples,
                          '여자인구수' : female_tuples})
korea_mdf

총인구수    남자인구수    여자인구수
서울특별시 2010  10312545  5111259  5201286
      2020   9720846  4732275  4988571
부산광역시 2010   2567910  1773170  1794740
      2020   3404423  1668618  1735805
인천광역시 2010   2758296  1390356  1367940
      2020   2947217  1476813  1470404
대구광역시 2010   2511676  1255245  1256431
      2020   2427954  1198815  1229139
대전광역시 2010   1503664   753648   750016
      2020   1471040   734441   736599
광주광역시 2010   1454636   721780   732856
      2020   1455048   720060   734988

In [93]:
ratio = korea_mdf['남자인구수'] * 100 / korea_mdf['여자인구수']
ratio

서울특별시  2010     98.269140
       2020     94.862336
부산광역시  2010     98.798155
       2020     96.129346
인천광역시  2010    101.638668
       2020    100.435867
대구광역시  2010     99.905606
       2020     97.532907
대전광역시  2010    100.484256
       2020     99.707032
광주광역시  2010     98.488653
       2020     97.968946
dtype: float64

In [94]:
ratio.unstack()

2010        2020
광주광역시   98.488653   97.968946
대구광역시   99.905606   97.532907
대전광역시  100.484256   99.707032
부산광역시   98.798155   96.129346
서울특별시   98.269140   94.862336
인천광역시  101.638668  100.435867

In [96]:
korea_mdf = pd.DataFrame({'총인구수' : population,
                          '남자인구수' : male_tuples,
                          '여자인구수' : female_tuples,
                          '남여비율' : ratio})
korea_mdf

총인구수    남자인구수    여자인구수        남여비율
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946

#### 다중 인덱스 생성

In [97]:
df = pd.DataFrame(np.random.rand(6, 3),
                  index = [['a', 'a', 'b', 'b', 'c', 'c'], [1, 2, 1, 2, 1, 2]],
                  columns = ['c1', 'c2', 'c3'])
df

c1        c2        c3
a 1  0.621365  0.555065  0.750783
  2  0.263959  0.809632  0.526078
b 1  0.852847  0.795790  0.671709
  2  0.906946  0.005928  0.316446
c 1  0.770039  0.422355  0.485954
  2  0.742032  0.837612  0.110998

In [98]:
pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b', 'c', 'c'], [1, 2, 1, 2, 1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [101]:
pd.MultiIndex.from_tuples([('a', 1), ('a', 2), ('b', 1), ('b', 2), ('c', 1), ('c', 2)])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [103]:
pd.MultiIndex.from_product([['a', 'b', 'c'], [1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [104]:
pd.MultiIndex(levels = [['a', 'b', 'c'], [1, 2]],
              codes = [[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]]) 

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [105]:
population

서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [106]:
population.index.names = ['행정구역', '연도']
population

행정구역   연도  
서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [108]:
idx = pd.MultiIndex.from_product([['a', 'b', 'c'], [1, 2]],
                                names = ['name1', 'name2'])
cols = pd.MultiIndex.from_product([['c1', 'c2', 'c3'], [1, 2]],
                                names = ['col_names1', 'col_names2'])
data = np.round(np.random.randn(6, 6), 2)
mdf = pd.DataFrame(data, index = idx, columns = cols)
mdf

col_names1     c1          c2          c3      
col_names2      1     2     1     2     1     2
name1 name2                                    
a     1      0.96 -1.64  0.93 -0.05  0.83  0.96
      2      0.11  0.19 -0.40  0.20 -1.74  0.83
b     1     -0.91  0.78  1.34 -0.51 -0.20 -1.12
      2      0.82  1.84  0.29 -1.18  0.73 -1.19
c     1      0.12  0.48  0.55 -0.49 -1.15 -0.10
      2      0.03  0.53  0.14  1.08  0.24  0.96

In [109]:
mdf['c2']

col_names2      1     2
name1 name2            
a     1      0.93 -0.05
      2     -0.40  0.20
b     1      1.34 -0.51
      2      0.29 -1.18
c     1      0.55 -0.49
      2      0.14  1.08

#### 인덱싱 및 슬라이싱

In [110]:
population

행정구역   연도  
서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [111]:
population['인천광역시', 2010]

2758296

In [112]:
population[:, 2010]

행정구역
서울특별시    10312545
부산광역시     2567910
인천광역시     2758296
대구광역시     2511676
대전광역시     1503664
광주광역시     1454636
dtype: int64

In [113]:
population[population > 3000000]

행정구역   연도  
서울특별시  2010    10312545
       2020     9720846
부산광역시  2020     3404423
dtype: int64

In [114]:
population[['대구광역시', '대전광역시']]

행정구역   연도  
대구광역시  2010    2511676
       2020    2427954
대전광역시  2010    1503664
       2020    1471040
dtype: int64

In [115]:
mdf

col_names1     c1          c2          c3      
col_names2      1     2     1     2     1     2
name1 name2                                    
a     1      0.96 -1.64  0.93 -0.05  0.83  0.96
      2      0.11  0.19 -0.40  0.20 -1.74  0.83
b     1     -0.91  0.78  1.34 -0.51 -0.20 -1.12
      2      0.82  1.84  0.29 -1.18  0.73 -1.19
c     1      0.12  0.48  0.55 -0.49 -1.15 -0.10
      2      0.03  0.53  0.14  1.08  0.24  0.96

In [116]:
mdf['c2',1]

name1  name2
a      1        0.93
       2       -0.40
b      1        1.34
       2        0.29
c      1        0.55
       2        0.14
Name: (c2, 1), dtype: float64

In [117]:
mdf.iloc[:3, :4]

col_names1     c1          c2      
col_names2      1     2     1     2
name1 name2                        
a     1      0.96 -1.64  0.93 -0.05
      2      0.11  0.19 -0.40  0.20
b     1     -0.91  0.78  1.34 -0.51

In [118]:
mdf.loc[:, ('c2', 1)]

name1  name2
a      1        0.93
       2       -0.40
b      1        1.34
       2        0.29
c      1        0.55
       2        0.14
Name: (c2, 1), dtype: float64

In [119]:
idx_slice = pd.IndexSlice
mdf.loc[idx_slice[:, 2], idx_slice[:, 2]]

col_names1     c1    c2    c3
col_names2      2     2     2
name1 name2                  
a     2      0.19  0.20  0.83
b     2      1.84 -1.18 -1.19
c     2      0.53  1.08  0.96

#### 다중 인덱스 재정렬

In [120]:
idx

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           names=['name1', 'name2'])

In [121]:
korea_mdf

총인구수    남자인구수    여자인구수        남여비율
행정구역  연도                                          
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946

In [123]:
#korea_mdf['서울특별시':'인천광역시']

korea_mdf = korea_mdf.sort_index()
korea_mdf

총인구수    남자인구수    여자인구수        남여비율
행정구역  연도                                          
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [124]:
korea_mdf['서울특별시':'인천광역시']

총인구수    남자인구수    여자인구수        남여비율
행정구역  연도                                          
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [128]:
korea_mdf.unstack(level = 0)

총인구수                                                 남자인구수           \
행정구역    광주광역시    대구광역시    대전광역시    부산광역시     서울특별시    인천광역시   광주광역시    대구광역시   
연도                                                                             
2010  1454636  2511676  1503664  2567910  10312545  2758296  721780  1255245   
2020  1455048  2427954  1471040  3404423   9720846  2947217  720060  1198815   

                       ...   여자인구수                                  남여비율  \
행정구역   대전광역시    부산광역시  ...   대전광역시    부산광역시    서울특별시    인천광역시      광주광역시   
연도                     ...                                                 
2010  753648  1773170  ...  750016  1794740  5201286  1367940  98.488653   
2020  734441  1668618  ...  736599  1735805  4988571  1470404  97.968946   

                                                               
행정구역      대구광역시       대전광역시      부산광역시      서울특별시       인천광역시  
연도                                                             
2010  99.905606  100.484256  98.798155  98.269140  101.638668  
2020  97.532907   99.707032  96.129346  94.862336  100.435867  

[2 rows x 24 columns]

In [129]:
korea_mdf.unstack(level = 1)

총인구수             남자인구수             여자인구수                 남여비율  \
연도         2010     2020     2010     2020     2010     2020        2010   
행정구역                                                                       
광주광역시   1454636  1455048   721780   720060   732856   734988   98.488653   
대구광역시   2511676  2427954  1255245  1198815  1256431  1229139   99.905606   
대전광역시   1503664  1471040   753648   734441   750016   736599  100.484256   
부산광역시   2567910  3404423  1773170  1668618  1794740  1735805   98.798155   
서울특별시  10312545  9720846  5111259  4732275  5201286  4988571   98.269140   
인천광역시   2758296  2947217  1390356  1476813  1367940  1470404  101.638668   

                   
연도           2020  
행정구역               
광주광역시   97.968946  
대구광역시   97.532907  
대전광역시   99.707032  
부산광역시   96.129346  
서울특별시   94.862336  
인천광역시  100.435867

In [130]:
korea_mdf.stack()

행정구역   연도         
광주광역시  2010  총인구수     1.454636e+06
             남자인구수    7.217800e+05
             여자인구수    7.328560e+05
             남여비율     9.848865e+01
       2020  총인구수     1.455048e+06
             남자인구수    7.200600e+05
             여자인구수    7.349880e+05
             남여비율     9.796895e+01
대구광역시  2010  총인구수     2.511676e+06
             남자인구수    1.255245e+06
             여자인구수    1.256431e+06
             남여비율     9.990561e+01
       2020  총인구수     2.427954e+06
             남자인구수    1.198815e+06
             여자인구수    1.229139e+06
             남여비율     9.753291e+01
대전광역시  2010  총인구수     1.503664e+06
             남자인구수    7.536480e+05
             여자인구수    7.500160e+05
             남여비율     1.004843e+02
       2020  총인구수     1.471040e+06
             남자인구수    7.344410e+05
             여자인구수    7.365990e+05
             남여비율     9.970703e+01
부산광역시  2010  총인구수     2.567910e+06
             남자인구수    1.773170e+06
             여자인구수    1.794740e+06
             남여비율     9.879815e+01
 

In [131]:
korea_mdf

총인구수    남자인구수    여자인구수        남여비율
행정구역  연도                                          
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [133]:
idx_flat = korea_mdf.reset_index(level = 0)
idx_flat

행정구역      총인구수    남자인구수    여자인구수        남여비율
연도                                                 
2010  광주광역시   1454636   721780   732856   98.488653
2020  광주광역시   1455048   720060   734988   97.968946
2010  대구광역시   2511676  1255245  1256431   99.905606
2020  대구광역시   2427954  1198815  1229139   97.532907
2010  대전광역시   1503664   753648   750016  100.484256
2020  대전광역시   1471040   734441   736599   99.707032
2010  부산광역시   2567910  1773170  1794740   98.798155
2020  부산광역시   3404423  1668618  1735805   96.129346
2010  서울특별시  10312545  5111259  5201286   98.269140
2020  서울특별시   9720846  4732275  4988571   94.862336
2010  인천광역시   2758296  1390356  1367940  101.638668
2020  인천광역시   2947217  1476813  1470404  100.435867

In [135]:
idx_flat = korea_mdf.reset_index(level = (0, 1))
idx_flat

행정구역    연도      총인구수    남자인구수    여자인구수        남여비율
0   광주광역시  2010   1454636   721780   732856   98.488653
1   광주광역시  2020   1455048   720060   734988   97.968946
2   대구광역시  2010   2511676  1255245  1256431   99.905606
3   대구광역시  2020   2427954  1198815  1229139   97.532907
4   대전광역시  2010   1503664   753648   750016  100.484256
5   대전광역시  2020   1471040   734441   736599   99.707032
6   부산광역시  2010   2567910  1773170  1794740   98.798155
7   부산광역시  2020   3404423  1668618  1735805   96.129346
8   서울특별시  2010  10312545  5111259  5201286   98.269140
9   서울특별시  2020   9720846  4732275  4988571   94.862336
10  인천광역시  2010   2758296  1390356  1367940  101.638668
11  인천광역시  2020   2947217  1476813  1470404  100.435867

In [136]:
idx_flat.set_index(['행정구역', '연도'])

총인구수    남자인구수    여자인구수        남여비율
행정구역  연도                                          
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

## 데이터 연산

In [137]:
s = pd.Series(np.random.randint(0, 10 ,5))
s

0    1
1    8
2    4
3    9
4    1
dtype: int32

In [138]:
df = pd.DataFrame(np.random.randint(0, 10 ,(3, 3)),
                  columns = ['A', 'B', 'C'])
df

A  B  C
0  5  0  5
1  2  5  2
2  9  6  3

In [139]:
np.exp(s)

0       2.718282
1    2980.957987
2      54.598150
3    8103.083928
4       2.718282
dtype: float64

In [140]:
np.cos(df * np.pi / 4)

A             B             C
0 -7.071068e-01  1.000000e+00 -7.071068e-01
1  6.123234e-17 -7.071068e-01  6.123234e-17
2  7.071068e-01 -1.836970e-16 -7.071068e-01

In [141]:
s1 = pd.Series([1, 3, 5, 7, 9], index = [0, 1, 2, 3, 4])
s2 = pd.Series([2, 4, 6, 8, 10], index = [1, 2, 3, 4, 5])
s1 + s2

0     NaN
1     5.0
2     9.0
3    13.0
4    17.0
5     NaN
dtype: float64

In [142]:
s1.add(s2, fill_value = 0)

0     1.0
1     5.0
2     9.0
3    13.0
4    17.0
5    10.0
dtype: float64

In [144]:
df1 = pd.DataFrame(np.random.randint(0, 20, (3, 3)),
                  columns = list('ACD'))
df1

A   C  D
0  14   1  1
1   0  10  0
2  14  17  4

In [146]:
df2 = pd.DataFrame(np.random.randint(0, 20, (5, 5)),
                  columns = list('BAECD'))
df2

B   A   E   C   D
0  17  19  10  16  18
1   9  11  17   8  16
2   6  17  17  13   9
3   2  10  15   4  14
4   4  19  16   7  18

In [147]:
df1 + df2

A   B     C     D   E
0  33.0 NaN  17.0  19.0 NaN
1  11.0 NaN  18.0  16.0 NaN
2  31.0 NaN  30.0  13.0 NaN
3   NaN NaN   NaN   NaN NaN
4   NaN NaN   NaN   NaN NaN

In [148]:
fvalue = df1.stack().mean()
df1.add(df2, fill_value = fvalue)

A          B          C          D          E
0  33.000000  23.777778  17.000000  19.000000  16.777778
1  11.000000  15.777778  18.000000  16.000000  23.777778
2  31.000000  12.777778  30.000000  13.000000  23.777778
3  16.777778   8.777778  10.777778  20.777778  21.777778
4  25.777778  10.777778  13.777778  24.777778  22.777778

### 연산자 범용 함수


|Python 연산자|Pandas 메소드|
|:--|:--|
|`+`|`add`, `rand` |
|`-`|`sub`, `rsub`, `subtract`|
|`*`|`mul`. `rmul`, `multiply`|
|`/`|`truediv`. `div`, `rdiv`, `divide`|
|`//`|`floordiv`, `rfloordiv`|
|`%`|`mod`|
|`**`|`pow`, `rpow`|

#### add()

In [149]:
a = np.random.randint(1, 10, (3, 3))
a

array([[2, 9, 5],
       [1, 5, 2],
       [4, 5, 6]])

In [150]:
a + a[0]

array([[ 4, 18, 10],
       [ 3, 14,  7],
       [ 6, 14, 11]])

In [151]:
df = pd.DataFrame(a, columns = list('ABC'))
df

A  B  C
0  2  9  5
1  1  5  2
2  4  5  6

In [155]:
df + df.iloc[0]

A   B   C
0  4  18  10
1  3  14   7
2  6  14  11

In [156]:
df.add(df.iloc[0])

A   B   C
0  4  18  10
1  3  14   7
2  6  14  11

#### sub() / subtract()

In [157]:
a

array([[2, 9, 5],
       [1, 5, 2],
       [4, 5, 6]])

In [158]:
a - a[0]

array([[ 0,  0,  0],
       [-1, -4, -3],
       [ 2, -4,  1]])

In [159]:
df

A  B  C
0  2  9  5
1  1  5  2
2  4  5  6

In [160]:
df - df.iloc[0]

A  B  C
0  0  0  0
1 -1 -4 -3
2  2 -4  1

In [162]:
df.sub(df.iloc[0])

A  B  C
0  0  0  0
1 -1 -4 -3
2  2 -4  1

In [163]:
df.subtract(df['B'], axis = 0)

A  B  C
0 -7  0 -4
1 -4  0 -3
2 -1  0  1

#### mul() / multply()




In [164]:
a

array([[2, 9, 5],
       [1, 5, 2],
       [4, 5, 6]])

In [165]:
a * a[0]

array([[ 4, 81, 25],
       [ 2, 45, 10],
       [ 8, 45, 30]])

In [166]:
df

A  B  C
0  2  9  5
1  1  5  2
2  4  5  6

In [167]:
df * df.iloc[1]

A   B   C
0  2  45  10
1  1  25   4
2  4  25  12

In [169]:
df.mul(df.iloc[1])

A   B   C
0  2  45  10
1  1  25   4
2  4  25  12

In [170]:
df.multiply(df.iloc[2])

A   B   C
0   8  45  30
1   4  25  12
2  16  25  36

#### truediv() /  div() / divide() / floordiv()

In [171]:
a

array([[2, 9, 5],
       [1, 5, 2],
       [4, 5, 6]])

In [172]:
a / a[0]

array([[1.        , 1.        , 1.        ],
       [0.5       , 0.55555556, 0.4       ],
       [2.        , 0.55555556, 1.2       ]])

In [173]:
df

A  B  C
0  2  9  5
1  1  5  2
2  4  5  6

In [174]:
df / df.iloc[0]

A         B    C
0  1.0  1.000000  1.0
1  0.5  0.555556  0.4
2  2.0  0.555556  1.2

In [175]:
df.truediv(df.iloc[0])

A         B    C
0  1.0  1.000000  1.0
1  0.5  0.555556  0.4
2  2.0  0.555556  1.2

In [176]:
df.div(df.iloc[1])

A    B    C
0  2.0  1.8  2.5
1  1.0  1.0  1.0
2  4.0  1.0  3.0

In [177]:
df.divide(df.iloc[2])

A    B         C
0  0.50  1.8  0.833333
1  0.25  1.0  0.333333
2  1.00  1.0  1.000000

In [178]:
a // a[0]

array([[1, 1, 1],
       [0, 0, 0],
       [2, 0, 1]], dtype=int32)

In [179]:
df.floordiv(df.iloc[0])

A  B  C
0  1  1  1
1  0  0  0
2  2  0  1

#### mod()

In [180]:
a

array([[2, 9, 5],
       [1, 5, 2],
       [4, 5, 6]])

In [181]:
a % a[0]

array([[0, 0, 0],
       [1, 5, 2],
       [0, 5, 1]], dtype=int32)

In [183]:
df

A  B  C
0  2  9  5
1  1  5  2
2  4  5  6

In [184]:
df.mod(df.iloc[0])

A  B  C
0  0  0  0
1  1  5  2
2  0  5  1

#### pow()

In [185]:
a

array([[2, 9, 5],
       [1, 5, 2],
       [4, 5, 6]])

In [186]:
a ** a[0]

array([[        4, 387420489,      3125],
       [        1,   1953125,        32],
       [       16,   1953125,      7776]], dtype=int32)

In [187]:
df

A  B  C
0  2  9  5
1  1  5  2
2  4  5  6

In [188]:
df.pow(df.iloc[0])

A          B     C
0   4  387420489  3125
1   1    1953125    32
2  16    1953125  7776

In [189]:
row = df.iloc[0, ::2]
row

A    2
C    5
Name: 0, dtype: int32

In [190]:
df - row

A   B    C
0  0.0 NaN  0.0
1 -1.0 NaN -3.0
2  2.0 NaN  1.0

### 정렬(Sort)

In [192]:
s = pd.Series(range(5), index = ['A', 'D', 'B', 'C', 'E'])
s

A    0
D    1
B    2
C    3
E    4
dtype: int64

In [193]:
s.sort_index()

A    0
B    2
C    3
D    1
E    4
dtype: int64

In [194]:
s.sort_values()

A    0
D    1
B    2
C    3
E    4
dtype: int64

In [197]:
df = pd.DataFrame(np.random.randint(0, 10, (4, 4)),
                  index = [2, 4, 1, 3],
                  columns = list('BDAC'))
df

B  D  A  C
2  3  9  5  6
4  5  9  9  5
1  8  2  9  4
3  7  6  2  5

In [198]:
df.sort_index()

B  D  A  C
1  8  2  9  4
2  3  9  5  6
3  7  6  2  5
4  5  9  9  5

In [203]:
df.sort_index(axis = 1)

A  B  C  D
2  5  3  6  9
4  9  5  5  9
1  9  8  4  2
3  2  7  5  6

In [201]:
df.sort_values(by = 'A')

B  D  A  C
3  7  6  2  5
2  3  9  5  6
4  5  9  9  5
1  8  2  9  4

In [202]:
df.sort_values(by = ['A', 'C'])

B  D  A  C
3  7  6  2  5
2  3  9  5  6
1  8  2  9  4
4  5  9  9  5

### 순위(Ranking)


|메소드|설명|
|:---|:---|
|`average`|기본값,순위에 같은 값을 가지는 항목들의 평균값을 사용|
|`min`|같은 값을 가지는 그룹을 낮은 순위로 지정|
|`max`|같은 값을 가지는 그룹을 높은 순위로 지정|
|`first`|데이터 내의 위치에 따라 순위 지정|
|`dense`|같은 그룹 내에서 모두 같은 순위를 적용하지 않고 1씩 증가|

In [204]:
s = pd.Series([-2, 4, 7, 3, 4, 5, 1, -7, 5, -9])
s

0   -2
1    4
2    7
3    3
4    4
5    5
6    1
7   -7
8    5
9   -9
dtype: int64

In [205]:
s.rank()

0     3.0
1     6.5
2    10.0
3     5.0
4     6.5
5     8.5
6     4.0
7     2.0
8     8.5
9     1.0
dtype: float64

In [206]:
s.rank(method = 'first')

0     3.0
1     6.0
2    10.0
3     5.0
4     7.0
5     8.0
6     4.0
7     2.0
8     9.0
9     1.0
dtype: float64

In [207]:
s.rank(method = 'max')

0     3.0
1     7.0
2    10.0
3     5.0
4     7.0
5     9.0
6     4.0
7     2.0
8     9.0
9     1.0
dtype: float64

### 고성능 연산

In [208]:
nrows, ncols = 100000, 100
df1, df2, df3, df4 = (pd.DataFrame(np.random.rand(nrows, ncols)) for i in range(4))

In [209]:
%timeit df1 + df2 + df3 + df4

55 ms ± 402 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [210]:
%timeit pd.eval('df1 + df2 + df3 + df4')

26.6 ms ± 480 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [211]:
%timeit df1 * -df2 / (-df3 * df4)

97.5 ms ± 641 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [212]:
%timeit pd.eval('df1 * -df2 / (-df3 * df4)')

27.5 ms ± 517 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [214]:
%timeit (df1 < df2) & (df2 <= df3) & (df3 != df4)

38.2 ms ± 585 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [215]:
%timeit pd.eval('(df1 < df2) & (df2 <= df3) & (df3 != df4)')

22.1 ms ± 127 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [216]:
df = pd.DataFrame(np.random.rand(1000000, 5), columns = ['A', 'B', 'C', 'D', 'E'])
df.head()

A         B         C         D         E
0  0.117450  0.320868  0.406688  0.774101  0.342196
1  0.550667  0.184767  0.003594  0.927135  0.192258
2  0.263442  0.123101  0.472896  0.953035  0.607449
3  0.078710  0.204863  0.100962  0.143647  0.828533
4  0.606261  0.620573  0.338378  0.028342  0.364419

In [217]:
%timeit df['A'] + df['B'] / df['C'] - df['D'] * df['E']

14 ms ± 192 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [220]:
%timeit pd.eval('df.A + df.B / df.C - df.D * df.E')

5.22 ms ± 168 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [221]:
%timeit df.eval('A + B / C - D * E')

8.49 ms ± 160 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [222]:
df.eval('R = A + B / C - D * E', inplace = True)
df.head()

A         B         C         D         E          R
0  0.117450  0.320868  0.406688  0.774101  0.342196   0.641534
1  0.550667  0.184767  0.003594  0.927135  0.192258  51.784492
2  0.263442  0.123101  0.472896  0.953035  0.607449  -0.055165
3  0.078710  0.204863  0.100962  0.143647  0.828533   1.988800
4  0.606261  0.620573  0.338378  0.028342  0.364419   2.429897

In [223]:
df.eval('R = A - B / C + D * E', inplace = True)
df.head()

A         B         C         D         E          R
0  0.117450  0.320868  0.406688  0.774101  0.342196  -0.406634
1  0.550667  0.184767  0.003594  0.927135  0.192258 -50.683158
2  0.263442  0.123101  0.472896  0.953035  0.607449   0.582049
3  0.078710  0.204863  0.100962  0.143647  0.828533  -1.831380
4  0.606261  0.620573  0.338378  0.028342  0.364419  -1.217376

In [224]:
col_mean = df.mean(1)
df['A'] + col_mean

0         0.376561
1        -7.586789
2         0.763770
3        -0.000401
4         0.729693
            ...   
999995    0.890148
999996    1.431506
999997    1.227758
999998   -1.658402
999999    0.179493
Length: 1000000, dtype: float64

In [225]:
df.eval('A + @col_mean')

0         0.376561
1        -7.586789
2         0.763770
3        -0.000401
4         0.729693
            ...   
999995    0.890148
999996    1.431506
999997    1.227758
999998   -1.658402
999999    0.179493
Length: 1000000, dtype: float64

In [226]:
df[(df.A < 0.5) & (df.B < 0.5) & (df.C > 0.5)]

A         B         C         D         E         R
39      0.427937  0.236832  0.894108  0.977931  0.986442  1.127729
40      0.281697  0.246955  0.587132  0.311450  0.165676 -0.087316
48      0.352090  0.423438  0.752666  0.727383  0.967136  0.492986
66      0.021525  0.400604  0.563457  0.947118  0.375264 -0.334032
67      0.120834  0.286529  0.952715  0.178797  0.044553 -0.171951
...          ...       ...       ...       ...       ...       ...
999959  0.248820  0.495237  0.632955  0.419670  0.297124 -0.408906
999968  0.119160  0.037364  0.909987  0.378420  0.701337  0.343501
999972  0.181860  0.340989  0.788299  0.173746  0.344163 -0.190907
999991  0.118179  0.328258  0.837326  0.748146  0.054356 -0.233186
999993  0.255174  0.251038  0.784664  0.517330  0.208238  0.042972

[125422 rows x 6 columns]

In [228]:
pd.eval('df[(df.A < 0.5) & (df.B < 0.5) & (df.C > 0.5)]')

A         B         C         D         E         R
39      0.427937  0.236832  0.894108  0.977931  0.986442  1.127729
40      0.281697  0.246955  0.587132  0.311450  0.165676 -0.087316
48      0.352090  0.423438  0.752666  0.727383  0.967136  0.492986
66      0.021525  0.400604  0.563457  0.947118  0.375264 -0.334032
67      0.120834  0.286529  0.952715  0.178797  0.044553 -0.171951
...          ...       ...       ...       ...       ...       ...
999959  0.248820  0.495237  0.632955  0.419670  0.297124 -0.408906
999968  0.119160  0.037364  0.909987  0.378420  0.701337  0.343501
999972  0.181860  0.340989  0.788299  0.173746  0.344163 -0.190907
999991  0.118179  0.328258  0.837326  0.748146  0.054356 -0.233186
999993  0.255174  0.251038  0.784664  0.517330  0.208238  0.042972

[125422 rows x 6 columns]

In [230]:
df.query('(A < 0.5) & (B < 0.5) & (C > 0.5)')

A         B         C         D         E         R
39      0.427937  0.236832  0.894108  0.977931  0.986442  1.127729
40      0.281697  0.246955  0.587132  0.311450  0.165676 -0.087316
48      0.352090  0.423438  0.752666  0.727383  0.967136  0.492986
66      0.021525  0.400604  0.563457  0.947118  0.375264 -0.334032
67      0.120834  0.286529  0.952715  0.178797  0.044553 -0.171951
...          ...       ...       ...       ...       ...       ...
999959  0.248820  0.495237  0.632955  0.419670  0.297124 -0.408906
999968  0.119160  0.037364  0.909987  0.378420  0.701337  0.343501
999972  0.181860  0.340989  0.788299  0.173746  0.344163 -0.190907
999991  0.118179  0.328258  0.837326  0.748146  0.054356 -0.233186
999993  0.255174  0.251038  0.784664  0.517330  0.208238  0.042972

[125422 rows x 6 columns]

In [231]:
col_mean = df['D'].mean()
df[(df.A < col_mean) & (df.B < col_mean)]

A         B         C         D         E          R
0       0.117450  0.320868  0.406688  0.774101  0.342196  -0.406634
2       0.263442  0.123101  0.472896  0.953035  0.607449   0.582049
3       0.078710  0.204863  0.100962  0.143647  0.828533  -1.831380
30      0.292136  0.117458  0.195943  0.331917  0.413498  -0.170064
33      0.224163  0.219391  0.178717  0.654197  0.456369  -0.704871
...          ...       ...       ...       ...       ...        ...
999990  0.403622  0.396497  0.258819  0.760960  0.274508  -0.919435
999991  0.118179  0.328258  0.837326  0.748146  0.054356  -0.233186
999992  0.078674  0.034907  0.001600  0.838573  0.798887 -21.066833
999993  0.255174  0.251038  0.784664  0.517330  0.208238   0.042972
999999  0.034907  0.327586  0.361570  0.823410  0.104829  -0.784788

[250055 rows x 6 columns]

In [232]:
df.query('A < @col_mean and B < @col_mean')

A         B         C         D         E          R
0       0.117450  0.320868  0.406688  0.774101  0.342196  -0.406634
2       0.263442  0.123101  0.472896  0.953035  0.607449   0.582049
3       0.078710  0.204863  0.100962  0.143647  0.828533  -1.831380
30      0.292136  0.117458  0.195943  0.331917  0.413498  -0.170064
33      0.224163  0.219391  0.178717  0.654197  0.456369  -0.704871
...          ...       ...       ...       ...       ...        ...
999990  0.403622  0.396497  0.258819  0.760960  0.274508  -0.919435
999991  0.118179  0.328258  0.837326  0.748146  0.054356  -0.233186
999992  0.078674  0.034907  0.001600  0.838573  0.798887 -21.066833
999993  0.255174  0.251038  0.784664  0.517330  0.208238   0.042972
999999  0.034907  0.327586  0.361570  0.823410  0.104829  -0.784788

[250055 rows x 6 columns]

## 데이터 결합

### Concat() / Append()

In [234]:
s1 = pd.Series(['a' , 'b'], index = [1, 2])
s2 = pd.Series(['c' , 'd'], index = [3, 4])
pd.concat([s1, s2])

1    a
2    b
3    c
4    d
dtype: object

In [235]:
def create_df(cols, idx):
    data = {c: [str(c.lower()) + str(i) for i in idx] for c in cols}
    return pd.DataFrame(data, idx)

In [236]:
df1 = create_df('AB', [1, 2])
df1

A   B
1  a1  b1
2  a2  b2

In [237]:
df2 = create_df('AB', [3, 4])
df2

A   B
3  a3  b3
4  a4  b4

In [238]:
pd.concat([df1, df2])

A   B
1  a1  b1
2  a2  b2
3  a3  b3
4  a4  b4

In [239]:
df3 = create_df('AB', [0, 1])
df3

A   B
0  a0  b0
1  a1  b1

In [240]:
df4 = create_df('CD', [0, 1])
df4

C   D
0  c0  d0
1  c1  d1

In [241]:
pd.concat([df3, df4])

A    B    C    D
0   a0   b0  NaN  NaN
1   a1   b1  NaN  NaN
0  NaN  NaN   c0   d0
1  NaN  NaN   c1   d1

In [248]:
pd.concat([df3, df4], axis = 1)

A   B   C   D
0  a0  b0  c0  d0
1  a1  b1  c1  d1

In [251]:
pd.concat([df1, df3])

A   B
1  a1  b1
2  a2  b2
0  a0  b0
1  a1  b1

In [250]:
#pd.concat([df1, df3], verify_integrity = True)

In [243]:
pd.concat([df1, df3], ignore_index = True)

A   B
0  a1  b1
1  a2  b2
2  a0  b0
3  a1  b1

In [244]:
pd.concat([df1,df3], keys = ['X', 'Y'])

A   B
X 1  a1  b1
  2  a2  b2
Y 0  a0  b0
  1  a1  b1

In [245]:
df5 = create_df('ABC', [1, 2])
df6 = create_df('BCD', [3, 4])
pd.concat([df5, df6])

A   B   C    D
1   a1  b1  c1  NaN
2   a2  b2  c2  NaN
3  NaN  b3  c3   d3
4  NaN  b4  c4   d4

In [246]:
pd.concat([df5, df6], join = 'inner')

B   C
1  b1  c1
2  b2  c2
3  b3  c3
4  b4  c4

In [247]:
df5.append(df6)

A   B   C    D
1   a1  b1  c1  NaN
2   a2  b2  c2  NaN
3  NaN  b3  c3   d3
4  NaN  b4  c4   d4

### 병합과 조인

In [253]:
df1 = pd.DataFrame({'학생' : ['홍길동', '이순신', '임꺽정', '김유신'],
                    '학과' : ['경영학과', '교육학과', '컴퓨터학과', '통계학과']})
df1

학생     학과
0  홍길동   경영학과
1  이순신   교육학과
2  임꺽정  컴퓨터학과
3  김유신   통계학과

In [254]:
df2 = pd.DataFrame({'학생' : ['홍길동', '이순신', '임꺽정', '김유신'],
                     '입학년도' : [2012, 2016, 2019, 2020]})
df2

학생  입학년도
0  홍길동  2012
1  이순신  2016
2  임꺽정  2019
3  김유신  2020

In [256]:
df3 = pd.merge(df1, df2)
df3

학생     학과  입학년도
0  홍길동   경영학과  2012
1  이순신   교육학과  2016
2  임꺽정  컴퓨터학과  2019
3  김유신   통계학과  2020

In [259]:
df4 = pd.DataFrame({'학과' : ['경영학과', '교육학과', '컴퓨터학과', '통계학과'],
                    '학과장' : ['황희', '장영실', '안창호', '정약용']})
df4

학과  학과장
0   경영학과   황희
1   교육학과  장영실
2  컴퓨터학과  안창호
3   통계학과  정약용

In [260]:
pd.merge(df3, df4)

학생     학과  입학년도  학과장
0  홍길동   경영학과  2012   황희
1  이순신   교육학과  2016  장영실
2  임꺽정  컴퓨터학과  2019  안창호
3  김유신   통계학과  2020  정약용

In [261]:
df5 = pd.DataFrame({'학과' : ['경영학과', '교육학과', '교육학과', '컴퓨터학과', '컴퓨터학과', '통계학과'],
                    '과목' : ['경영개론', '기초수학', '물리학', '프로그래밍', '운영체제', '확률론']})
df5

학과     과목
0   경영학과   경영개론
1   교육학과   기초수학
2   교육학과    물리학
3  컴퓨터학과  프로그래밍
4  컴퓨터학과   운영체제
5   통계학과    확률론

In [262]:
pd.merge(df1, df5)

학생     학과     과목
0  홍길동   경영학과   경영개론
1  이순신   교육학과   기초수학
2  이순신   교육학과    물리학
3  임꺽정  컴퓨터학과  프로그래밍
4  임꺽정  컴퓨터학과   운영체제
5  김유신   통계학과    확률론

In [265]:
pd.merge(df1, df2, on='학생')

학생     학과  입학년도
0  홍길동   경영학과  2012
1  이순신   교육학과  2016
2  임꺽정  컴퓨터학과  2019
3  김유신   통계학과  2020

In [266]:
df6 = pd.DataFrame({'이름' : ['홍길동', '이순신', '임꺽정', '김유신'],
                    '성적' : ['A', 'A+', 'B', 'A+']})
df6

이름  성적
0  홍길동   A
1  이순신  A+
2  임꺽정   B
3  김유신  A+

In [267]:
pd.merge(df1, df6, left_on="학생", right_on="이름")

학생     학과   이름  성적
0  홍길동   경영학과  홍길동   A
1  이순신   교육학과  이순신  A+
2  임꺽정  컴퓨터학과  임꺽정   B
3  김유신   통계학과  김유신  A+

In [268]:
pd.merge(df1, df6, left_on="학생", right_on="이름").drop("이름", axis = 1)

학생     학과  성적
0  홍길동   경영학과   A
1  이순신   교육학과  A+
2  임꺽정  컴퓨터학과   B
3  김유신   통계학과  A+

In [269]:
mdf1 = df1.set_index('학생')
mdf2 = df2.set_index('학생')

In [270]:
mdf1

학과
학생        
홍길동   경영학과
이순신   교육학과
임꺽정  컴퓨터학과
김유신   통계학과

In [271]:
mdf2

입학년도
학생       
홍길동  2012
이순신  2016
임꺽정  2019
김유신  2020

In [272]:
pd.merge(mdf1, mdf2, left_index = True, right_index = True)

학과  입학년도
학생              
홍길동   경영학과  2012
이순신   교육학과  2016
임꺽정  컴퓨터학과  2019
김유신   통계학과  2020

In [273]:
mdf1.join(mdf2)

학과  입학년도
학생              
홍길동   경영학과  2012
이순신   교육학과  2016
임꺽정  컴퓨터학과  2019
김유신   통계학과  2020

In [274]:
pd.merge(mdf1, df6, left_index = True, right_on = '이름')

학과   이름  성적
0   경영학과  홍길동   A
1   교육학과  이순신  A+
2  컴퓨터학과  임꺽정   B
3   통계학과  김유신  A+

In [275]:
df7 = pd.DataFrame({'이름' : ['홍길동', '이순신', '임꺽정'],
                    '주문음식' : ['햄버거', '피자', '짜장면']})
df7

이름 주문음식
0  홍길동  햄버거
1  이순신   피자
2  임꺽정  짜장면

In [276]:
df8 = pd.DataFrame({'이름' : ['홍길동', '이순신', '김유신'],
                    '주문음료' : ['콜라', '사이다', '커피']})
df8

이름 주문음료
0  홍길동   콜라
1  이순신  사이다
2  김유신   커피

In [277]:
pd.merge(df7, df8)

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다

## 데이터 집계와 그룹 연산

#### 집계 연산(Aggregation)


### GroupBy 연산

### 피벗 테이블(Pivot Table)


### 범주형(Categorical) 데이터


## 문자열 연산

#### 문자열 연산자

#### 기타 연산자


#### 정규표현식


## 시계열 처리

#### 시계열 데이터 구조


### 시계열 기본

### 주기와 오프셋


### 시프트(Shift)

### 시간대 처리

* 국제표준시(Coordinated Universal Time, UTC)를 기준으로 떨어진 거리만큼 오프셋으로 시간대 처리
* 전 세계의 시간대 정보를 모아놓은 올슨 데이터베이스를 활용한 라이브러리인 `pytz` 사용

### 기간과 기간 연산

### 리샘플링(Resampling)

* 리샘플링(Resampling): 시계열의 빈도 변환
* 다운샘플링(Down sampling): 상위 빈도 데이터를 하위 빈도 데이터로 집계
* 업샘플링(Up sampling): 하위 빈도 데이터를 상위 빈도 데이터로 집계

### 무빙 윈도우(Moving Window)

## 데이터 읽기 및 저장


### 텍스트 파일 읽기/쓰기

### 이진 데이터 파일 읽기/쓰기

## 데이터 정제

### 누락값 처리

* 대부분의 실제 데이터들은 정제되지 않고 누락값들이 존재
* 서로 다른 데이터들은 다른 형태의 결측을 가짐
* 결측 데이터는 `null`, `NaN`, `NA`로 표기

#### None: 파이썬 누락 데이터

#### NaN: 누락된 수치 데이터

#### Null 값 처리


### 중복 제거

### 값 치환

## 참고문헌

* Pandas 사이트: https://pandas.pydata.org/
* Jake VanderPlas, "Python Data Science Handbook", O'Reilly
* Wes Mckinney, "Python for Data Analysis", O'Reilly